# 是否开启短命令打开市场, 例如: /market
short-command: true
# 玩家售出物品后的税率, 1% = 0.01
tax:
  default: 0.1
  vip: 0.05
# 日期格式
simple-date-format: "yyyy/MM/dd HH:mm:ss"
# 物品上架黑名单
black-list:
  type:
    - "STONE"
  lore:
    - "&f禁止上架"
# 价格范围
price:
  min: 1
  max: 2000000
# 上架物品是否公告
sale-broadcast: true
# 是否开启商品额外信息
sale-info: true